### ISSUE TITLE
MapExtractor

### ISSUE THREAD

**Issue by Smerdokryl** [ProjectSkyfire/SkyFire-Community-Tools#12]
Hi!
I recently compiled the core and downloaded this tool pack. Neither the map extractor compiled with the core, nor the one in this pack work properly for me. They just close straight away on startup without extracting anything

**Comment by Smerdokryl** [comment]
Never mind, only the extractor from the core doesn't work. Apparently, when trying the tool pack extractors, I didn't completely copy them over and was still using the other one

**Comment by SkyFire** [comment]
The extractor works fine. It could be the fact you are using using a Russian version to extract from. I do know of some issues. But I don't have a Russian client to test. I may look into this in the next few days.
